<Project>
  <PropertyGroup>
    <ModRefsDir Condition="'$(ModRefsDir)' == '' And Exists('$(MSBuildThisFileDirectory)..\ModRefs')">$(MSBuildThisFileDirectory)..\ModRefs\</ModRefsDir>
    <ModRefsDir Condition="'$(ModRefsDir)' == '' And Exists('$(MSBuildThisFileDirectory)..\..\ModRefs')">$(MSBuildThisFileDirectory)..\..\ModRefs\</ModRefsDir>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="0Harmony">
      <HintPath>$(ModRefsDir)0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="AsmResolver">
      <HintPath>$(ModRefsDir)AsmResolver.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="AsmResolver.DotNet">
      <HintPath>$(ModRefsDir)AsmResolver.DotNet.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="AsmResolver.PE">
      <HintPath>$(ModRefsDir)AsmResolver.PE.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="AsmResolver.PE.File">
      <HintPath>$(ModRefsDir)AsmResolver.PE.File.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(ModRefsDir)Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Assembly-CSharp-firstpass">
      <HintPath>$(ModRefsDir)Assembly-CSharp-firstpass.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="AssetRipper.Primitives">
      <HintPath>$(ModRefsDir)AssetRipper.Primitives.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="AssetsTools.NET">
      <HintPath>$(ModRefsDir)AssetsTools.NET.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="bHapticsLib">
      <HintPath>$(ModRefsDir)bHapticsLib.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Iced">
      <HintPath>$(ModRefsDir)Iced.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Il2CppAmazingAssets.AdvancedDissolve">
      <HintPath>$(ModRefsDir)Il2CppAmazingAssets.AdvancedDissolve.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Il2CppAmazingAssets.AdvancedDissolve.Examples">
      <HintPath>$(ModRefsDir)Il2CppAmazingAssets.AdvancedDissolve.Examples.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Il2CppDOTween">
      <HintPath>$(ModRefsDir)Il2CppDOTween.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Il2CppGUPS.Obfuscator">
      <HintPath>$(ModRefsDir)Il2CppGUPS.Obfuscator.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Il2CppInterop.Common">
      <HintPath>$(ModRefsDir)Il2CppInterop.Common.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Il2CppInterop.Generator">
      <HintPath>$(ModRefsDir)Il2CppInterop.Generator.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Il2CppInterop.HarmonySupport">
      <HintPath>$(ModRefsDir)Il2CppInterop.HarmonySupport.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Il2CppInterop.Runtime">
      <HintPath>$(ModRefsDir)Il2CppInterop.Runtime.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Il2CppLinework">
      <HintPath>$(ModRefsDir)Il2CppLinework.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Il2CppMono.Security">
      <HintPath>$(ModRefsDir)Il2CppMono.Security.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Il2CppSirenix.OdinInspector.Attributes">
      <HintPath>$(ModRefsDir)Il2CppSirenix.OdinInspector.Attributes.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Il2CppSirenix.Serialization">
      <HintPath>$(ModRefsDir)Il2CppSirenix.Serialization.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Il2CppSirenix.Serialization.Config">
      <HintPath>$(ModRefsDir)Il2CppSirenix.Serialization.Config.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Il2CppSirenix.Utilities">
      <HintPath>$(ModRefsDir)Il2CppSirenix.Utilities.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Il2CppSystem">
      <HintPath>$(ModRefsDir)Il2CppSystem.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Il2CppSystem.Configuration">
      <HintPath>$(ModRefsDir)Il2CppSystem.Configuration.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Il2CppSystem.Core">
      <HintPath>$(ModRefsDir)Il2CppSystem.Core.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Il2CppSystem.Xml">
      <HintPath>$(ModRefsDir)Il2CppSystem.Xml.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Il2CppUnified.Universal.Blur">
      <HintPath>$(ModRefsDir)Il2CppUnified.Universal.Blur.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Il2CppZenject">
      <HintPath>$(ModRefsDir)Il2CppZenject.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Il2CppZenject-usage">
      <HintPath>$(ModRefsDir)Il2CppZenject-usage.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Il2Cpp__Generated">
      <HintPath>$(ModRefsDir)Il2Cpp__Generated.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Il2Cppmscorlib">
      <HintPath>$(ModRefsDir)Il2Cppmscorlib.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="IndexRange">
      <HintPath>$(ModRefsDir)IndexRange.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="MelonLoader">
      <HintPath>$(ModRefsDir)MelonLoader.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="MelonLoader.NativeHost">
      <HintPath>$(ModRefsDir)MelonLoader.NativeHost.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Microsoft.Bcl.AsyncInterfaces">
      <HintPath>$(ModRefsDir)Microsoft.Bcl.AsyncInterfaces.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Microsoft.Bcl.Memory">
      <HintPath>$(ModRefsDir)Microsoft.Bcl.Memory.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Microsoft.Diagnostics.NETCore.Client">
      <HintPath>$(ModRefsDir)Microsoft.Diagnostics.NETCore.Client.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Microsoft.Diagnostics.Runtime">
      <HintPath>$(ModRefsDir)Microsoft.Diagnostics.Runtime.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Microsoft.Extensions.Configuration">
      <HintPath>$(ModRefsDir)Microsoft.Extensions.Configuration.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Microsoft.Extensions.Configuration.Abstractions">
      <HintPath>$(ModRefsDir)Microsoft.Extensions.Configuration.Abstractions.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Microsoft.Extensions.DependencyInjection">
      <HintPath>$(ModRefsDir)Microsoft.Extensions.DependencyInjection.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Microsoft.Extensions.DependencyInjection.Abstractions">
      <HintPath>$(ModRefsDir)Microsoft.Extensions.DependencyInjection.Abstractions.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Microsoft.Extensions.Logging">
      <HintPath>$(ModRefsDir)Microsoft.Extensions.Logging.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Microsoft.Extensions.Logging.Abstractions">
      <HintPath>$(ModRefsDir)Microsoft.Extensions.Logging.Abstractions.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Microsoft.Extensions.Options">
      <HintPath>$(ModRefsDir)Microsoft.Extensions.Options.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Microsoft.Extensions.Primitives">
      <HintPath>$(ModRefsDir)Microsoft.Extensions.Primitives.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Mono.Cecil">
      <HintPath>$(ModRefsDir)Mono.Cecil.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Mono.Cecil.Mdb">
      <HintPath>$(ModRefsDir)Mono.Cecil.Mdb.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Mono.Cecil.Pdb">
      <HintPath>$(ModRefsDir)Mono.Cecil.Pdb.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Mono.Cecil.Rocks">
      <HintPath>$(ModRefsDir)Mono.Cecil.Rocks.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="MonoMod">
      <HintPath>$(ModRefsDir)MonoMod.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="MonoMod.Backports">
      <HintPath>$(ModRefsDir)MonoMod.Backports.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="MonoMod.ILHelpers">
      <HintPath>$(ModRefsDir)MonoMod.ILHelpers.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="MonoMod.RuntimeDetour">
      <HintPath>$(ModRefsDir)MonoMod.RuntimeDetour.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="MonoMod.Utils">
      <HintPath>$(ModRefsDir)MonoMod.Utils.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>$(ModRefsDir)Newtonsoft.Json.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="System.Configuration.ConfigurationManager">
      <HintPath>$(ModRefsDir)System.Configuration.ConfigurationManager.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="System.Diagnostics.DiagnosticSource">
      <HintPath>$(ModRefsDir)System.Diagnostics.DiagnosticSource.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="System.Runtime.CompilerServices.Unsafe">
      <HintPath>$(ModRefsDir)System.Runtime.CompilerServices.Unsafe.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="System.Security.Cryptography.ProtectedData">
      <HintPath>$(ModRefsDir)System.Security.Cryptography.ProtectedData.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="System.Security.Permissions">
      <HintPath>$(ModRefsDir)System.Security.Permissions.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Tomlet">
      <HintPath>$(ModRefsDir)Tomlet.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Unity.Burst">
      <HintPath>$(ModRefsDir)Unity.Burst.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Unity.Burst.Unsafe">
      <HintPath>$(ModRefsDir)Unity.Burst.Unsafe.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Unity.Cinemachine">
      <HintPath>$(ModRefsDir)Unity.Cinemachine.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Unity.Collections">
      <HintPath>$(ModRefsDir)Unity.Collections.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Unity.Collections.LowLevel.ILSupport">
      <HintPath>$(ModRefsDir)Unity.Collections.LowLevel.ILSupport.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Unity.InputSystem">
      <HintPath>$(ModRefsDir)Unity.InputSystem.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Unity.InputSystem.ForUI">
      <HintPath>$(ModRefsDir)Unity.InputSystem.ForUI.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Unity.Mathematics">
      <HintPath>$(ModRefsDir)Unity.Mathematics.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Unity.MemoryProfiler">
      <HintPath>$(ModRefsDir)Unity.MemoryProfiler.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Unity.RenderPipeline.Universal.ShaderLibrary">
      <HintPath>$(ModRefsDir)Unity.RenderPipeline.Universal.ShaderLibrary.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Unity.RenderPipelines.Core.Runtime">
      <HintPath>$(ModRefsDir)Unity.RenderPipelines.Core.Runtime.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Unity.RenderPipelines.Core.Runtime.Shared">
      <HintPath>$(ModRefsDir)Unity.RenderPipelines.Core.Runtime.Shared.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Unity.RenderPipelines.GPUDriven.Runtime">
      <HintPath>$(ModRefsDir)Unity.RenderPipelines.GPUDriven.Runtime.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Unity.RenderPipelines.Universal.2D.Runtime">
      <HintPath>$(ModRefsDir)Unity.RenderPipelines.Universal.2D.Runtime.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Unity.RenderPipelines.Universal.Runtime">
      <HintPath>$(ModRefsDir)Unity.RenderPipelines.Universal.Runtime.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Unity.Splines">
      <HintPath>$(ModRefsDir)Unity.Splines.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Unity.TextMeshPro">
      <HintPath>$(ModRefsDir)Unity.TextMeshPro.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Unity.Timeline">
      <HintPath>$(ModRefsDir)Unity.Timeline.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Unity.VisualScripting.Core">
      <HintPath>$(ModRefsDir)Unity.VisualScripting.Core.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>$(ModRefsDir)UnityEngine.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.AIModule">
      <HintPath>$(ModRefsDir)UnityEngine.AIModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.ARModule">
      <HintPath>$(ModRefsDir)UnityEngine.ARModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.AccessibilityModule">
      <HintPath>$(ModRefsDir)UnityEngine.AccessibilityModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.AndroidJNIModule">
      <HintPath>$(ModRefsDir)UnityEngine.AndroidJNIModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.AnimationModule">
      <HintPath>$(ModRefsDir)UnityEngine.AnimationModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.AssetBundleModule">
      <HintPath>$(ModRefsDir)UnityEngine.AssetBundleModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.AudioModule">
      <HintPath>$(ModRefsDir)UnityEngine.AudioModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.ClothModule">
      <HintPath>$(ModRefsDir)UnityEngine.ClothModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.ContentLoadModule">
      <HintPath>$(ModRefsDir)UnityEngine.ContentLoadModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(ModRefsDir)UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.CrashReportingModule">
      <HintPath>$(ModRefsDir)UnityEngine.CrashReportingModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.DSPGraphModule">
      <HintPath>$(ModRefsDir)UnityEngine.DSPGraphModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.DirectorModule">
      <HintPath>$(ModRefsDir)UnityEngine.DirectorModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.GIModule">
      <HintPath>$(ModRefsDir)UnityEngine.GIModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.GameCenterModule">
      <HintPath>$(ModRefsDir)UnityEngine.GameCenterModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.GraphicsStateCollectionSerializerModule">
      <HintPath>$(ModRefsDir)UnityEngine.GraphicsStateCollectionSerializerModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.GridModule">
      <HintPath>$(ModRefsDir)UnityEngine.GridModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.HierarchyCoreModule">
      <HintPath>$(ModRefsDir)UnityEngine.HierarchyCoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.HotReloadModule">
      <HintPath>$(ModRefsDir)UnityEngine.HotReloadModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.IMGUIModule">
      <HintPath>$(ModRefsDir)UnityEngine.IMGUIModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.Il2CppAssetBundleManager">
      <HintPath>$(ModRefsDir)UnityEngine.Il2CppAssetBundleManager.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.Il2CppImageConversionManager">
      <HintPath>$(ModRefsDir)UnityEngine.Il2CppImageConversionManager.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.ImageConversionModule">
      <HintPath>$(ModRefsDir)UnityEngine.ImageConversionModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.InputForUIModule">
      <HintPath>$(ModRefsDir)UnityEngine.InputForUIModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.InputLegacyModule">
      <HintPath>$(ModRefsDir)UnityEngine.InputLegacyModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.InputModule">
      <HintPath>$(ModRefsDir)UnityEngine.InputModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.JSONSerializeModule">
      <HintPath>$(ModRefsDir)UnityEngine.JSONSerializeModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.LocalizationModule">
      <HintPath>$(ModRefsDir)UnityEngine.LocalizationModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.MarshallingModule">
      <HintPath>$(ModRefsDir)UnityEngine.MarshallingModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.MultiplayerModule">
      <HintPath>$(ModRefsDir)UnityEngine.MultiplayerModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.ParticleSystemModule">
      <HintPath>$(ModRefsDir)UnityEngine.ParticleSystemModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.PerformanceReportingModule">
      <HintPath>$(ModRefsDir)UnityEngine.PerformanceReportingModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.Physics2DModule">
      <HintPath>$(ModRefsDir)UnityEngine.Physics2DModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>$(ModRefsDir)UnityEngine.PhysicsModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.PropertiesModule">
      <HintPath>$(ModRefsDir)UnityEngine.PropertiesModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.RuntimeInitializeOnLoadManagerInitializerModule">
      <HintPath>$(ModRefsDir)UnityEngine.RuntimeInitializeOnLoadManagerInitializerModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.ScreenCaptureModule">
      <HintPath>$(ModRefsDir)UnityEngine.ScreenCaptureModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.ShaderVariantAnalyticsModule">
      <HintPath>$(ModRefsDir)UnityEngine.ShaderVariantAnalyticsModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.SharedInternalsModule">
      <HintPath>$(ModRefsDir)UnityEngine.SharedInternalsModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.SpriteMaskModule">
      <HintPath>$(ModRefsDir)UnityEngine.SpriteMaskModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.SpriteShapeModule">
      <HintPath>$(ModRefsDir)UnityEngine.SpriteShapeModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.StreamingModule">
      <HintPath>$(ModRefsDir)UnityEngine.StreamingModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.SubstanceModule">
      <HintPath>$(ModRefsDir)UnityEngine.SubstanceModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.SubsystemsModule">
      <HintPath>$(ModRefsDir)UnityEngine.SubsystemsModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.TLSModule">
      <HintPath>$(ModRefsDir)UnityEngine.TLSModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.TerrainModule">
      <HintPath>$(ModRefsDir)UnityEngine.TerrainModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.TerrainPhysicsModule">
      <HintPath>$(ModRefsDir)UnityEngine.TerrainPhysicsModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.TextCoreFontEngineModule">
      <HintPath>$(ModRefsDir)UnityEngine.TextCoreFontEngineModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.TextCoreTextEngineModule">
      <HintPath>$(ModRefsDir)UnityEngine.TextCoreTextEngineModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.TextRenderingModule">
      <HintPath>$(ModRefsDir)UnityEngine.TextRenderingModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.TilemapModule">
      <HintPath>$(ModRefsDir)UnityEngine.TilemapModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>$(ModRefsDir)UnityEngine.UI.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.UIElementsModule">
      <HintPath>$(ModRefsDir)UnityEngine.UIElementsModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.UIModule">
      <HintPath>$(ModRefsDir)UnityEngine.UIModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.UmbraModule">
      <HintPath>$(ModRefsDir)UnityEngine.UmbraModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.UnityAnalyticsCommonModule">
      <HintPath>$(ModRefsDir)UnityEngine.UnityAnalyticsCommonModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.UnityAnalyticsModule">
      <HintPath>$(ModRefsDir)UnityEngine.UnityAnalyticsModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.UnityConnectModule">
      <HintPath>$(ModRefsDir)UnityEngine.UnityConnectModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.UnityCurlModule">
      <HintPath>$(ModRefsDir)UnityEngine.UnityCurlModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.UnityTestProtocolModule">
      <HintPath>$(ModRefsDir)UnityEngine.UnityTestProtocolModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.UnityWebRequestAssetBundleModule">
      <HintPath>$(ModRefsDir)UnityEngine.UnityWebRequestAssetBundleModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.UnityWebRequestAudioModule">
      <HintPath>$(ModRefsDir)UnityEngine.UnityWebRequestAudioModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.UnityWebRequestModule">
      <HintPath>$(ModRefsDir)UnityEngine.UnityWebRequestModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.UnityWebRequestTextureModule">
      <HintPath>$(ModRefsDir)UnityEngine.UnityWebRequestTextureModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.UnityWebRequestWWWModule">
      <HintPath>$(ModRefsDir)UnityEngine.UnityWebRequestWWWModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.VFXModule">
      <HintPath>$(ModRefsDir)UnityEngine.VFXModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.VRModule">
      <HintPath>$(ModRefsDir)UnityEngine.VRModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.VehiclesModule">
      <HintPath>$(ModRefsDir)UnityEngine.VehiclesModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.VideoModule">
      <HintPath>$(ModRefsDir)UnityEngine.VideoModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.WindModule">
      <HintPath>$(ModRefsDir)UnityEngine.WindModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.XRModule">
      <HintPath>$(ModRefsDir)UnityEngine.XRModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="FruitLib">
      <HintPath>$(ModRefsDir)FruitLib.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="WebSocketDotNet">
      <HintPath>$(ModRefsDir)WebSocketDotNet.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
